module2-task1 Нужно больше функций
htmlacademy-javascript/1520009-keksobooking-1 pull request #2
Opened 2023-09-29 13:33 UTC by werdnaapil

Второе Домашнее задание, в комментариях есть пара вопросов-сомнений, прошу глянуть

2023-09-29 21:00 UTC, ekazakov requested changes

2023-09-29 21:00 UTC, ekazakov commented on js/function.js
> +window.console.log(isPalindrom('Ро тор'));
Можно писать просто `console.log`

2023-09-29 21:00 UTC, ekazakov commented on js/function.js
> +// вроде результат есть но мы еще реверс массивов не проходили
Можешь решать задачи любым удобным способом. Главное чтобы самому было понятно.
Единственное ограничение — нельзя использовать сторонние библиотеки, кроме тех, что есть по проекту

2023-09-29 21:00 UTC, ekazakov commented on js/function.js
> +  return (parseInt(result, 10)); //возвращаем результат из строки в виде целых чисел в десятично исчислении
Скобки вокруг `parseInt` не нужны

2023-09-29 21:00 UTC, ekazakov commented on js/function.js
> +  const string = arg.toString();
Можно не конвертировать `arg` в строку, по заданию мы уверены, что это всегда строка.
В реальных проектах проверка делается входящих данных делается по другому. На созвоне можем обсудить.

2023-09-29 21:00 UTC, ekazakov commented on js/function.js
> +Настроить реакцию если буде указан диапазон так что первое число меньше второго */
Тоже обсудим

2023-09-29 21:00 UTC, ekazakov commented on index.html
> +  <script src = "function.js"></script>
Путь до файла должен быть `js/fucntion.js` т.к. файл лежит в папке `js`

2023-09-30 18:23 UTC, werdnaapil commented on js/function.js
> +window.console.log(isPalindrom('Ро тор'));
Если пиcать console.log то линтер не пропустит

2023-09-30 20:02 UTC, ekazakov commented on js/function.js
> +window.console.log(isPalindrom('Ро тор'));
В целом замечания линтера не мешают принятию задачи, их можно игнорировать или глушить через комментарий `// eslint-disable-next-line`

2023-09-30 20:03 UTC, merged